### ISSUE TITLE
Environment won't load - can't delete or launch - get an error

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/try-code-builder-feedback#143]
**Describe the bug**
Code Builder environment won't load.  The dashboard won't allow me to launch and throws an error when I try to delete.

**To Reproduce**
1. Create a new DE Org
2. Installed Code Builder
3. Code Builder was setup with a connection to the org I launched from and a clone of a public github repo.
4. Spent some time on various tasks in CB - SOQL Builder, Org Browser, Deploy, coding, etc
5. Closed the browser tab
6. Next day, I tried to relaunch from the URL (https://kale-dstrognsm2.builder.code.com/) - i get an error and message that the site can't be reached
7. Then I logged back into my org to launch CB from the dashboard.
8. Video attached shows the flow once I'm in CB dashboard

Two errors seen:

This one when I open or refresh Code Builder dashboard:

> CodeBuilder.ResourceApiResponseException
> 
> There was an error communicating with the workspace. Try again later. If you still encounter errors, contact Support and provide the error details.
> ```
> 409 {
>   "statusCode": 409,
>   "error": "Conflict",
>   "message": "ERROR: No waitlist record found for userId: 0058c0000071hvnAAA, orgId: 00D8c000006h4bSEAQ"
> }
> 
> ```

and this one when I try to delete:

> CodeBuilder.ResourceApiResponseException
> 
> There was an error communicating with the workspace. Try again later. If you still encounter errors, contact Support and provide the error details.
> ```
> 500 Internal server error
> ```

**Expected behavior**
I can launch my environment.  If I can't launch my environment, allowing me to delete it would be a workaround.  (although not ideal because i will have lost any work if i forgot to save to source control or an Org)

https://user-images.githubusercontent.com/59572234/162490530-07292ac3-4ac5-4d66-b86e-236a54582e39.mp4

**Comment by smaddox-sf** [comment]
might be related to #127

**Comment by jgellin-sf** [comment]
We suspect that this is not related to https://github.com/forcedotcom/try-code-builder-feedback/issues/127. We suspect that the problem is that the delete flows from notifications, and since notifications weren't flowing during blitz, the delete never happened. However, there will always be some small gap between when someone runs out of usage and the delete finally flows from the notifications. In this gap we should detect this situation and allow a user to delete their environment.

**Comment by jheikes515** [comment]
Was able to reproduce this in CBD 0.9.0.4, so the modifications did not fix this issue.

**Comment by jheikes515** [comment]
Just confirmed that the above is true - once I received the email stating that my CB trial was over, I was able to return to the dashboard and the workspace had been deleted. This issue isn't gone, but now only appears to occur when CBD trial times out and the user goes back to CBD prior to the notification/workspace deletion. This isn't something that's likely to happen often with a standard, 20-hour trial, but _could_. So we need to consider further what to do to prevent this situation since it could come up in GA as well, when a user hits their usage limit for the month.

**Comment by smaddox-sf** [comment]
Thanks for tracking this down @jheikes515 !  Good to know that it seems to be an edge case for customer usage.

One question - So if I create a CB environment it and delete it before my time is up, it will be successful, right?  (meaning that I can delete without error and return to CB Dashboard and create a new CB environment without error)

**Comment by jheikes515** [comment]
@smaddox-sf Yes, I just verified that deletions work as expected if the environment has not yet expired. The bug now only happens if the user attempts to go back to it after expiry, but before the "beta finished - environment deleted" notification goes out.

**Comment by jheikes515** [comment]
I'm going through this again to check something else, and now I'm seeing the issue again. Still seeing the dialogs over an hour after my workspace was deleted, so this definitely needs further work.

**Comment by smaddox-sf** [comment]
@jheikes515 - Checking back on this...can it be closed?  From the prior comments, it seems like this has been pinned down to a very narrow edge case.  Is that right?

**Comment by jheikes515** [comment]
Stephanie - you are correct.

JENNETTE HEIKES
Lead Member of Technical Staff | Salesforce
Mobile: 937-623-4814
