### ISSUE TITLE
Frequent disconnect and attempt to reconnect

### ISSUE THREAD

**Issue by prateeksengar** [forcedotcom/try-code-builder-feedback#172]
**Describe the bug**
I am facing frequent disconnects of the environment and attempting to reconnect. Further the attempt to reconnect is not being successful, the only workaround is to refresh the browser, but that leads to loose in unsaved data.

**To Reproduce**
1. Go to 'Code builder environment'
2. Work in the environment "write apex code or LWC etc" for 15 min
3. See error

**Expected behavior**
Not see this reconnecting error

**Screenshots**
![Screen Shot 2022-07-25 at 12 44 53 PM](https://user-images.githubusercontent.com/3127811/180851825-c3ffc3b8-7792-4bb2-add2-9516eeacf1e1.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by eburtness** [comment]
I was just getting ready to open an issue on this—I've been seeing similar behavior:
- Disconnects happen even when I'm actively working, so it doesn't seem to be an inactivity timeout.
- Waiting for it to reconnect or choosing **Reconnect Now** has never succeeded for me.
- Choosing **Reload Window** takes me to the "Code Builder is starting up..." screen with pulsing Codey. After about 5 minutes, it seems to reload the Code Builder Dashboard for a second and then automatically launch back to "Code Builder is starting up..."
- I think sometimes it eventually loads, but usually I give up waiting after several minutes.
- The only way I've found to get back in is to close the browser tab, go back to the Code Builder Dashboard, and click the **Launch** button to open a new tab.

**Comment by smaddox-sf** [comment]
Thank you for trying out Code Builder and for reporting this.  We're investigating

**Comment by smaddox-sf** [comment]
Hi @prateeksengar and @eburtness - We've made changes that should have helped.  Can you let us know if you are still seeing issues?

**Comment by eburtness** [comment]
Hi @smaddox-sf - sorry I couldn't test right away. I used it for about 7 hours yesterday with no disconnects, so that seems fixed!! Thanks!

The one problem I did have was my environment disappeared altogether overnight. I created a new one this morning, and that disappeared mid-day today. The one today might have been because my time was up—is that expected that the environment just disappears once the allotted hours are spent? (Also it seems my 20 hours were used up in only about 11 hours of having it open, but I'm not too worried about that as I understand the limit is for balancing usage during the beta.)
