### ISSUE TITLE
Cannot integrate with our Enterprise Github

### ISSUE THREAD

**Issue by DanTong71** [forcedotcom/try-code-builder-feedback#175]
**Describe the bug**
Trying to import or link to our Enterprise Github (https://github.<our company>.com instead of generic github.com and it won't connect and when click on the "Authorize with GitHub" button, it only point to Github.com which is blocked by the enterprise proxy by default.

**Comment by jgellin-sf** [comment]
@DanTong71 Thanks for your interest in Code Builder.

In order to authorize Code Builder with GitHub, Code Builder has an OAuth app registered with public GitHub. Since Code Builder does not have OAuth apps registered with individual Enterprise GitHub instances, it cannot integrate with Enterprise GitHub in the same way. See https://github.com/forcedotcom/try-code-builder-feedback/wiki/Known-Gaps-and-Issues#cant-import-an-existing-github-enterprise-project for more information

As a workaround, create an empty project instead, and once you are in your Code Builder environment you can set up your connection to Enterprise GitHub, clone your projects, and switch to the relevant directories like you would on your own client machines.
