### ISSUE TITLE
Not able to authorize the org

### ISSUE THREAD

**Issue by nagmani88** [forcedotcom/try-code-builder-feedback#191]
Getting below error while authorizing an org :

ERROR: We can’t query your org. Make sure that you’re connected to this org and have permissions to view the object and fields.

**Comment by smaddox-sf** [comment]
Hi @nagmani88 - Can you share the steps you were going through when you hit this error?  Where you on the Code Builder Dashboard trying to setup a new environment?  Please share more info on the steps and your system so we can investigate:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Smartphone or other device (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
