### ISSUE TITLE
Auto-Save act weird

### ISSUE THREAD

**Issue by abhsax** [forcedotcom/try-code-builder-feedback#198]
Under File, I unchecked the Auto-Save option, and later when I modified the class it was checked again. I do not want to keep the Auto-Save always on and need proper control over it.

**Comment by smaddox-sf** [comment]
Hi @abhsax - Thanks for the feedback.  In Code Builder, Auto-save is turned on by default.  Because you are working in the cloud, we want to help protect you from losing any work, just in case you got disconnected.

That's interesting that it didn't respect your choice to turn it off though.  We'll look at this for GA to either disable this setting if we can't let you control it or respect your choice if it's available.

**Comment by floralan** [comment]
Hi @abhsax, this issue has been fixed in Code Builder. I'm going to close here. Please let us know if you have more questions. Thank you for trying Code Builder!
