### ISSUE TITLE
Ctrl+S should save and deploy my changes at the same time

### ISSUE THREAD

**Issue by abhsax** [forcedotcom/try-code-builder-feedback#199]
I need a feature where when I can enable Save and Deploy at the same time.
Say, if I press Ctrl+S (standard short key for save) then it should save the changes not only in code builder but at the same time push it to my org. Thanks!

**Comment by smaddox-sf** [comment]
Hi @abhsax - Thanks for trying out Code Builder and sharing your feedback.  As discussed on #198 , auto-save is always on in Code Builder to ensure changes are saved in case you get disconnected.  However this makes deploy-on-save not behave since it then tries to deploy extremely frequently.  

Is your request here to allow you to turn OFF Auto Save in Code Builder and turn ON Deploy-on-Save?


**Here's more info on the deploy-on-save setting in case that is unfamiliar:** 
Within the Salesforce Extensions (whether accessed from Code Builder or VS Code), there is a setting to automatically deploy on save.  To get to settings, you can execute the `Preferences: Open Settings (UI)` command.  Here's a visual on the setting I'm referring to:

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/59572234/198076802-7bba61e3-8f3f-46e3-9961-5c80f5524b49.png">

**Comment by abhsax** [comment]
As you mentioned, you are planning to keep the auto-save always on, and on top of it if I enable push-on save from preference settings, then the deployment frequency will be very high. I do not prefer this.

I would love to see auto-save off and deploy-on-manual-save on. So when auto-save is off and I press Ctrl+S then it saves in code builder and deploy as well.

**Comment by floralan** [comment]
Hi @abhsax, as we mentioned in #198, you can now turn off the auto-save setting. You are also able to turn on the deploy-on-save setting to have deployment when you press Ctrl+S. I'm going to close this issue. Please let us know if you have more questions.
